### ISSUE TITLE
Last GLPi versions have changed domains management

### ISSUE THREAD

**Issue by dzogrim** [pszafer/check_glpi_fia_lastinventory#1]
Hello,

I've upgraded GLPi to version 9.5.4 from version 9.4.5…
What was working perfectly with your program is now broken.
`CRITICAL - FIA doesn't exist for this host!`
And I think I found why:

https://github.com/pszafer/check_glpi_fia_lastinventory/blob/fe7bef64d790936d5af73d53115718fe753b096a/check_glpi_fia_lastinventory.pl#L169

Seems now the field might be **205**.
Could you check this please to support last versions?

Thanks,

Regards

-- 
Seb

**Comment by pszafer** [comment]
I will update my GLPI instance and let you know.

**Comment by pszafer** [comment]
It should be fixed. Let me know.

**Comment by dzogrim** [comment]
Great. Thanks.
